### ISSUE TITLE
Prettier lint errors

### ISSUE THREAD

**Issue by dbeff** [gabbes/eslint-config-react-native-typescript#1]
Hey! First of all, thank you for bring this all together and make my life way easier! 😃 

It seems that the prettier is not showing errors on eslint command. Is it possible to be included? It might not be an issue but as the package is already included I don't know why I don't get any errors.

**Comment by gabts** [comment]
Hello, sorry for delayed response!

I'm not sure I quite understand, do you mean that formatting errors (new lines, space after comma, etc) doesn't show up when running e.g: `npm run eslint .` ?

The config is setup to ignore any formatting that is taken care of by prettier (via [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)), and let prettier itself handle them, e.g by auto-formatting file on save or by running prettier over entire project.

I would suggest either running prettier on your project before eslint `npm run prettier && npm run eslint` or manually enabling the same ruleset in eslint as used in your prettier, but that would be a lot of work and since everyone have different prettier config wouldn't be something that would be added to this config. :)

Hope that answers your question, if not feel free elaborate! :-)

Thanks

**Comment by gabts** [comment]
Closing issue!
